/* Generated By:JavaCC: Do not edit this line. IlocParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IlocParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 5;
  /** RegularExpression Id. */
  int ADDI = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int C2C = 8;
  /** RegularExpression Id. */
  int C2I = 9;
  /** RegularExpression Id. */
  int CALL = 10;
  /** RegularExpression Id. */
  int CBR = 11;
  /** RegularExpression Id. */
  int CBRNE = 12;
  /** RegularExpression Id. */
  int CBR_LT = 13;
  /** RegularExpression Id. */
  int CBR_LE = 14;
  /** RegularExpression Id. */
  int CBR_EQ = 15;
  /** RegularExpression Id. */
  int CBR_NE = 16;
  /** RegularExpression Id. */
  int CBR_GT = 17;
  /** RegularExpression Id. */
  int CBR_GE = 18;
  /** RegularExpression Id. */
  int CLOADAI = 19;
  /** RegularExpression Id. */
  int CLOADAO = 20;
  /** RegularExpression Id. */
  int CLOAD = 21;
  /** RegularExpression Id. */
  int CMP_LT = 22;
  /** RegularExpression Id. */
  int CMP_LE = 23;
  /** RegularExpression Id. */
  int CMP_EQ = 24;
  /** RegularExpression Id. */
  int CMP_NE = 25;
  /** RegularExpression Id. */
  int CMP_GT = 26;
  /** RegularExpression Id. */
  int CMP_GE = 27;
  /** RegularExpression Id. */
  int COMP = 28;
  /** RegularExpression Id. */
  int CREAD = 29;
  /** RegularExpression Id. */
  int CSTOREAI = 30;
  /** RegularExpression Id. */
  int CSTOREAO = 31;
  /** RegularExpression Id. */
  int CSTORE = 32;
  /** RegularExpression Id. */
  int CWRITE = 33;
  /** RegularExpression Id. */
  int DATA = 34;
  /** RegularExpression Id. */
  int DIVI = 35;
  /** RegularExpression Id. */
  int DIV = 36;
  /** RegularExpression Id. */
  int F2F = 37;
  /** RegularExpression Id. */
  int F2I = 38;
  /** RegularExpression Id. */
  int FADD = 39;
  /** RegularExpression Id. */
  int FCALL = 40;
  /** RegularExpression Id. */
  int FCOMP = 41;
  /** RegularExpression Id. */
  int FDIV = 42;
  /** RegularExpression Id. */
  int FLOADAI = 43;
  /** RegularExpression Id. */
  int FLOADAO = 44;
  /** RegularExpression Id. */
  int FLOAD = 45;
  /** RegularExpression Id. */
  int FLOAT = 46;
  /** RegularExpression Id. */
  int FMULT = 47;
  /** RegularExpression Id. */
  int FRAME = 48;
  /** RegularExpression Id. */
  int FREAD = 49;
  /** RegularExpression Id. */
  int FRET = 50;
  /** RegularExpression Id. */
  int FWRITE = 51;
  /** RegularExpression Id. */
  int FSTOREAI = 52;
  /** RegularExpression Id. */
  int FSTOREAO = 53;
  /** RegularExpression Id. */
  int FSTORE = 54;
  /** RegularExpression Id. */
  int FSUB = 55;
  /** RegularExpression Id. */
  int GLOBAL = 56;
  /** RegularExpression Id. */
  int I2F = 57;
  /** RegularExpression Id. */
  int I2I = 58;
  /** RegularExpression Id. */
  int ICALL = 59;
  /** RegularExpression Id. */
  int IREAD = 60;
  /** RegularExpression Id. */
  int IRET = 61;
  /** RegularExpression Id. */
  int IWRITE = 62;
  /** RegularExpression Id. */
  int JUMPI = 63;
  /** RegularExpression Id. */
  int JUMP = 64;
  /** RegularExpression Id. */
  int LOADAI = 65;
  /** RegularExpression Id. */
  int LOADAO = 66;
  /** RegularExpression Id. */
  int LOAD = 67;
  /** RegularExpression Id. */
  int LOADI = 68;
  /** RegularExpression Id. */
  int LSHIFTI = 69;
  /** RegularExpression Id. */
  int LSHIFT = 70;
  /** RegularExpression Id. */
  int MOD = 71;
  /** RegularExpression Id. */
  int MULTI = 72;
  /** RegularExpression Id. */
  int MULT = 73;
  /** RegularExpression Id. */
  int NOP = 74;
  /** RegularExpression Id. */
  int NOT = 75;
  /** RegularExpression Id. */
  int OR = 76;
  /** RegularExpression Id. */
  int RSHIFTI = 77;
  /** RegularExpression Id. */
  int RSHIFT = 78;
  /** RegularExpression Id. */
  int RET = 79;
  /** RegularExpression Id. */
  int STOREAI = 80;
  /** RegularExpression Id. */
  int STOREAO = 81;
  /** RegularExpression Id. */
  int STORE = 82;
  /** RegularExpression Id. */
  int STRING = 83;
  /** RegularExpression Id. */
  int SUBI = 84;
  /** RegularExpression Id. */
  int SUB = 85;
  /** RegularExpression Id. */
  int SWRITE = 86;
  /** RegularExpression Id. */
  int TBL = 87;
  /** RegularExpression Id. */
  int TESTEQ = 88;
  /** RegularExpression Id. */
  int TESTGE = 89;
  /** RegularExpression Id. */
  int TESTGT = 90;
  /** RegularExpression Id. */
  int TESTLE = 91;
  /** RegularExpression Id. */
  int TESTLT = 92;
  /** RegularExpression Id. */
  int TESTNE = 93;
  /** RegularExpression Id. */
  int TEXT = 94;
  /** RegularExpression Id. */
  int ASSIGN = 95;
  /** RegularExpression Id. */
  int ARROW = 96;
  /** RegularExpression Id. */
  int COLON = 97;
  /** RegularExpression Id. */
  int SEMICOLON = 98;
  /** RegularExpression Id. */
  int LBRACKET = 99;
  /** RegularExpression Id. */
  int RBRACKET = 100;
  /** RegularExpression Id. */
  int COMMA = 101;
  /** RegularExpression Id. */
  int VR = 102;
  /** RegularExpression Id. */
  int STRING_CONST = 103;
  /** RegularExpression Id. */
  int LABEL = 104;
  /** RegularExpression Id. */
  int INITIAL = 105;
  /** RegularExpression Id. */
  int DOT = 106;
  /** RegularExpression Id. */
  int DIGIT = 107;
  /** RegularExpression Id. */
  int ALPHA = 108;
  /** RegularExpression Id. */
  int UNDERSCORE = 109;
  /** RegularExpression Id. */
  int FLOAT_CONST = 110;
  /** RegularExpression Id. */
  int NUMBER = 111;
  /** RegularExpression Id. */
  int EXPONENT = 112;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"add\"",
    "\"addI\"",
    "\"and\"",
    "\"c2c\"",
    "\"c2i\"",
    "\"call\"",
    "\"cbr\"",
    "\"cbrne\"",
    "\"cbr_LT\"",
    "\"cbr_LE\"",
    "\"cbr_EQ\"",
    "\"cbr_NE\"",
    "\"cbr_GT\"",
    "\"cbr_GE\"",
    "\"cloadAI\"",
    "\"cloadAO\"",
    "\"cload\"",
    "\"cmp_LT\"",
    "\"cmp_LE\"",
    "\"cmp_EQ\"",
    "\"cmp_NE\"",
    "\"cmp_GT\"",
    "\"cmp_GE\"",
    "\"comp\"",
    "\"cread\"",
    "\"cstoreAI\"",
    "\"cstoreAO\"",
    "\"cstore\"",
    "\"cwrite\"",
    "\".data\"",
    "\"divI\"",
    "\"div\"",
    "\"f2f\"",
    "\"f2i\"",
    "\"fadd\"",
    "\"fcall\"",
    "\"fcomp\"",
    "\"fdiv\"",
    "\"floadAI\"",
    "\"floadAO\"",
    "\"fload\"",
    "\".float\"",
    "\"fmult\"",
    "\".frame\"",
    "\"fread\"",
    "\"fret\"",
    "\"fwrite\"",
    "\"fstoreAI\"",
    "\"fstoreAO\"",
    "\"fstore\"",
    "\"fsub\"",
    "\".global\"",
    "\"i2f\"",
    "\"i2i\"",
    "\"icall\"",
    "\"iread\"",
    "\"iret\"",
    "\"iwrite\"",
    "\"jumpI\"",
    "\"jump\"",
    "\"loadAI\"",
    "\"loadAO\"",
    "\"load\"",
    "\"loadI\"",
    "\"lshiftI\"",
    "\"lshift\"",
    "\"mod\"",
    "\"multI\"",
    "\"mult\"",
    "\"nop\"",
    "\"not\"",
    "\"or\"",
    "\"rshiftI\"",
    "\"rshift\"",
    "\"ret\"",
    "\"storeAI\"",
    "\"storeAO\"",
    "\"store\"",
    "\".string\"",
    "\"subI\"",
    "\"sub\"",
    "\"swrite\"",
    "\"tbl\"",
    "\"testeq\"",
    "\"testge\"",
    "\"testgt\"",
    "\"testle\"",
    "\"testlt\"",
    "\"testne\"",
    "\".text\"",
    "\"=>\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "<VR>",
    "<STRING_CONST>",
    "<LABEL>",
    "<INITIAL>",
    "\".\"",
    "<DIGIT>",
    "<ALPHA>",
    "\"_\"",
    "<FLOAT_CONST>",
    "<NUMBER>",
    "<EXPONENT>",
  };

}
